# Generated by Django 2.2 on 2021-01-22 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
