# Generated by Django 2.2 on 2021-01-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
